name: CI

on:
  push:
    branches: [main]
  pull_request:
  release:

env:
  go-version: 1.17

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go-version }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.43

  bindings:
    name: Generate bindings
    runs-on: ubuntu-latest
    env:
      solc_version: 0.7.0
      abigen_version: 1.10.18
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go-version }}

      - name: Install solc
        run: |
          docker pull ethereum/solc:${{ env.solc_version }}
          alias solc='docker run ethereum/solc:${{ env.solc_version }}'
          solc --version

      - name: Install abigen
        run: | 
          go install github.com/ethereum/go-ethereum/cmd/abigen@v${{ env.abigen_version }}
          abigen --version

      - name: Generate bindings
        working-directory: ${{ env.repo_dir }}
        run: |
          cd bindings
          ./generate.sh

      - name: Test
        run: go test -timeout 60s ./...

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go-version }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore dependencies from cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: go test
        run: go test -timeout 60s ./...

  race-test:
    name: Race Test
    needs: bindings
    runs-on: ubuntu-latest
    steps:
      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go-version }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore dependencies from cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-race
          restore-keys: |
            ${{ runner.os }}-go-

      - name: go test -race
        run: go test -timeout 120s -race ./...
